# Generated by Django 4.2.20 on 2025-04-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routepoint',
            options={},
        ),
        migrations.RemoveField(
            model_name='routepoint',
            name='order',
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='x',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='y',
            field=models.PositiveIntegerField(),
        ),
    ]
